config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :carts
  resources :items
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'omni_auth'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

    get 'cards/show'
    get '/order-placed' =>"cards#success_page",as: :success_page
  resources :products

  resources :shops, only:[:index, :show]
  resources :order_items
  resource :cards, only:[:show]



  root 'shops#index'
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all

    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', shop_path(product) %></td>



        <td>


          <%= form_for @order_item, remote: true  do |f|%>
          <%= f.hidden_field :product_id, :value => product.id %>
          <%= f.number_field :quantity, :value => 1, :min =>  1%>
          <%= f.submit "Add to Card "%>


          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="card">
  <%= render 'cards/card'%>
</div>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<% @product.assignments.each do |assignment| %>

  <%= assignment.color.color %>
  <%= assignment.quantity %>

<% end %>

<%= link_to 'Back', root_path %>