config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :carts
  resources :items
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'omni_auth'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

    get 'cards/show'
    get '/order-placed' =>"cards#success_page",as: :success_page
  resources :products

  resources :shops, only:[:index, :show]
  resources :order_items
  resource :cards, only:[:show]



  root 'shops#index'
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
  def success_page
    @order_items = current_order.order_items
    @order_items.destroy
    session[:order_id] = nil
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<%= link_to "You have #{current_order.order_items.size} item(s) with a value of Rs #{current_order.subtotal } Click to Checkout", cards_path,class: "btn btn-primary" %>

app/views/cards/_cards_item.html.erb
<!-- <p>Your current card value has a subtotal of: <%#= current_order.subtotal %></p> -->

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
          <div class="table-responsive">
            <%if @order_items.present?%>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col"> </th>
                        <th scope="col">Product</th>
                        <th scope="col" class="text-center">Quantity</th>
                        <th scope="col" class="text-right">Price</th>
                        <th scope="col" class="text-right">Total</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                  <% @order_items.each do |item| %>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td><%= item.product.title %></td>
                        <td>
                          <%= form_for item, remote: true do |f| %>

                        <%= f.hidden_field :product_id, :value => item.product.id %>
                        <%= f.number_field :quantity, :value => item.quantity.to_i %>
                        <%= f.submit "Update Card "%>
                        </td>
                        <td class="text-right">&#x20B9; <%= item.product.price %> </td>
                        <td class="text-right">&#x20B9; <%= item.total %> </td>
                        <td class="text-right">


                        <%= link_to '<i class="fa fa-trash"></i>'.html_safe, order_item_path(item), method: :delete, remote: true,class: "btn btn-sm btn-danger"%>
                      <% end %>
                    </tr>
                  <%end%>
                  <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Sub-Total</td>
                        <td class="text-right">&#x20B9; <%= current_order.subtotal %></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Shipping</td>
                        <td class="text-right">&#x20B9; 0</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Total</strong></td>
                        <td class="text-right"><strong>&#x20B9; <%= current_order.subtotal %></strong></td>
                    </tr>
                </tbody>
            </table>
            <%end%>
          </div>
          </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                    <%= link_to "Continue Shopping", root_url,class: "btn btn-block btn-light" %>
                </div>
                <%if @order_items.present?%>
                <div class="col-sm-12 col-md-6 text-right">
                    <%= link_to "Checkout", success_page_path,class: "btn btn-lg btn-block btn-success text-uppercase" %>
                </div>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/cards/show.html.erb
<div id="card-item">
<%= render 'cards_item'%>
</div>

app/views/cards/success_page.html.erb
    <h2>Thanks For this order</h2>
  <h3>Order Placed Successfully on below address</h3>
  <p>Phone Number: <%=current_user.phone_number%></p>
  <p>Phone Number: <%=current_user.address%></p>